ci(tests): echo tests output on complete;

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -48,5 +48,5 @@ jobs:
               OUTPUT=$(nvim --headless -c "lua require('nordic.tests').run_tests()" -c 'q' 2>&1);
               if [[ -n "$OUTPUT" ]]
               then
-                exit 1
+                echo "::error title='Checks failed'::$OUTPUT" && exit 1
               fi
